export const SEND_USER_INFO = 'SEND_USER_INFO';
export const GET_TOPTEN_RANKING = 'GET_TOPTEN_RANKING';
export const GET_QUESTION = 'GET_QUESTION';
export const SEND_RESPONSE = 'SEND_RESPONSE';
export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const GET_FAVOURITES = 'GET_FAVOURITES';